### ISSUE TITLE
Convert classes with constructors to structs

### ISSUE THREAD

**Issue by golf1052** [signal-csharp/curve25519-dotnet#2]
There are probably potential performance gains to be had if the classes with constructors were structs instead.

[See .NET documentation](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct)

**Comment by Trolldemorted** [comment]
I haven't used c# structs extensively set, the big difference to classes is that they are not references types, right? So we'd have to check every function that takes a struct as an argument so that permutations in the callee are not lost.

**Comment by golf1052** [comment]
There are 5 classes with constructors
- Ge_p3
- Ge_p2
- Ge_precomp
- Ge_cached
- Ge_p1p1

All of them have a parameterless constructor which initializes the arrays contained within them. [Structs cannot implement a parameterless constructor and the default value for reference values, which is what arrays are, will be null](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct#limitations-with-the-design-of-a-structure-type). So turning these into structs wouldn't be of any use. Closing.
